version: '3.3'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin@qless
      POSTGRES_PASSWORD: admin@qless#159
      POSTGRES_DB: Qless